env:
  browser: true
  es6: true
  jest: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - babel
rules:
  semi:
    - 1
    - always
  arrow-body-style:
    - 1
    - as-needed
  space-before-function-paren:
    - 1
    - never
  comma-dangle:
    - 1
    - always-multiline
  prefer-template:
    - 1
